# This is a basic workflow to help you get started with Actions

name: Run some script in Kunpeng env

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run `uname -a` in Kunpeng env
      run: |
        uname -a
        sudo cat /proc/cmdline 
        ls /sys/fs/resctrl/
        cat /etc/os-release
        lscpu | grep -E "Architecture|Model name|CPU\(s\):"
        pwd
        path_work=/home/github/actions-runner/_work/kunpeng-mpam/kunpeng-mpam/.github/workflows
        sudo bash $path_work/ctrl_gnum_test.sh &> test_result.log
        cat test_result.log
        sudo rm -rf test_result.log
